development:
  adapter: postgresql
  encoding: unicode
  database: tweetwatch
  username: tweetwatch
  password: tweetwatch
  host: 0.0.0.0

test:
  adapter: postgresql
  encoding: unicode
  database: tweetwatch_test
  username: tweetwatch
  password: tweetwatch
  host: 0.0.0.0
